root := ../../..

target-libs := \
  mtr-utils \
  mtr-debug

shared-libs := $(target-libs)

shared-includes := \
  mtr-utils.inc \
  mtr-debug.inc \
  mtr-im2.inc

include $(root)/build/asm-lib.include

