#ifndef _MTR_TASK_CONTEXT_
#define _MTR_TASK_CONTEXT_

GLOBAL __mtr_task_ctr
#define mtr_task_ctr __mtr_task_ctr

GLOBAL __mtr_active_tasks_ctr
#define mtr_active_tasks_ctr __mtr_active_tasks_ctr

GLOBAL __mtr_current_task_ctx
#define mtr_current_task_ctx __mtr_current_task_ctx

GLOBAL __mtr_task_ctx_start
#define mtr_task_ctx_start __mtr_task_ctx_start

GLOBAL __mtr_task_ctx_end
#define mtr_task_ctx_end __mtr_task_ctx_end

#endif
